# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import file_repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0004_filemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=file_repository.models.get_file_name, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=256, verbose_name='name'),
        ),
    ]
