# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160723_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterUniqueTogether(
            name='userproblem',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userproblem',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='userproblem',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userproblem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
