# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_userproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gpg_key',
            field=models.TextField(blank=True, verbose_name='gpg key'),
        ),
    ]
