# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('runner', '0004_jobmodel_compile_job'), ('runner', '0005_jobmodel_isolate_message'), ('runner', '0006_jobmodel_execution_wall_clock_time'), ('runner', '0007_jobmodel_isolate_log')]

    dependencies = [
        ('runner', '0003_auto_20160806_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='compile_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='isolate_message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='execution_wall_clock_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='isolate_log',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
