# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0002_filemodel'),
        ('problems', '0002_auto_20160727_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='_compiled_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='compiled file'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_repository.FileModel', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='source file'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='_input_file',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='_input_uploaded_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='input uploaded file'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='_output_file',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='_output_uploaded_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='input file'),
        ),
    ]
