# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20160730_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='_input_generation_command',
            new_name='_input_generation_parameters',
        ),
        migrations.AddField(
            model_name='testcase',
            name='_input_generator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.SourceFile', verbose_name='generator'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='_solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.SourceFile', verbose_name='solution'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='_output_uploaded_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='output file'),
        ),
    ]
