# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 11:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20160723_1028'),
        ('problems', '0008_auto_20160824_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='posting date')),
                ('priority', models.CharField(choices=[('0', 'info - no effect on correctness '), ('1', 'low'), ('2', 'medium'), ('3', 'high')], max_length=100, verbose_name='priority')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'posting_date'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='problem',
        ),
        migrations.AddField(
            model_name='comment',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 28, 11, 28, 7, 737860, tzinfo=utc), verbose_name='last edit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='users',
            field=models.ManyToManyField(related_name='problems', through='accounts.UserProblem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.SourceFile', verbose_name='checker'),
        ),
        migrations.AlterField(
            model_name='problemrevision',
            name='depth',
            field=models.IntegerField(blank=True, verbose_name='revision depth'),
        ),
        migrations.AlterField(
            model_name='problemrevision',
            name='parent_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemRevision', verbose_name='parent revision'),
        ),
        migrations.AlterField(
            model_name='problemrevision',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.Problem', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='problems.Problem', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problems.Discussion', verbose_name='discussion'),
            preserve_default=False,
        ),
    ]
