# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0013_auto_20160914_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.PositiveIntegerField(null=True)),
                ('ours_id', models.PositiveIntegerField(null=True)),
                ('theirs_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemFork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='problemrevision',
            old_name='owner',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='problemrevision',
            name='problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemrevision',
            name='revision_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True, verbose_name='revision id'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.SourceFile', verbose_name='checker'),
        ),
        migrations.AddField(
            model_name='problemfork',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemRevision', verbose_name='head'),
        ),
        migrations.AddField(
            model_name='problemfork',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='fork owner'),
        ),
        migrations.AddField(
            model_name='problemfork',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='problems.Problem', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='merge',
            name='base_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision'),
        ),
        migrations.AddField(
            model_name='merge',
            name='merged_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges', to='problems.ProblemRevision'),
        ),
        migrations.AddField(
            model_name='merge',
            name='our_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision'),
        ),
        migrations.AddField(
            model_name='merge',
            name='their_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='merge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Merge'),
        ),
        migrations.AddField(
            model_name='problemrevision',
            name='fork',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemFork', verbose_name='fork'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='problemfork',
            unique_together=set([('owner', 'problem')]),
        ),
    ]
