# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_auto_20160922_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemrevision',
            name='parent_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision', verbose_name='parent revision'),
        ),
    ]
