# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('problems', '0016_auto_20160922_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflict',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='problemrevision',
            name='fork',
        ),
        migrations.RemoveField(
            model_name='problemrevision',
            name='parent_revision',
        ),
        migrations.AddField(
            model_name='conflict',
            name='current_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='ours_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conflict',
            name='theirs_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='problemrevision',
            name='parent_revisions',
            field=models.ManyToManyField(related_name='_problemrevision_parent_revisions_+', to='problems.ProblemRevision', verbose_name='parent revisions'),
        ),
        migrations.AddField(
            model_name='problemrevision',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='problems.Problem', verbose_name='problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemRevision'),
        ),
        migrations.AlterField(
            model_name='problemfork',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision', verbose_name='head'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='_input_generation_parameters',
            field=models.TextField(blank=True, max_length=1, verbose_name='input generation command'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='_input_generator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.SourceFile', verbose_name='generator'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='_output_uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='output file'),
        ),
    ]
