# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_auto_20161002_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemrevision',
            name='commit_message',
            field=models.TextField(default='', verbose_name='commit message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemfork',
            name='working_copy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision', verbose_name='working copy'),
        ),
    ]
