# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_auto_20161003_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merge',
            name='merged_revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merge_result', to='problems.ProblemRevision'),
        ),
    ]
