# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0023_testcase_testcase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.Solution', verbose_name='solution'),
        ),
    ]
