# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0029_auto_20161025_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='should_be_present_verdicts',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('crashed', 'Crashed'), ('nonzero_exit_code', 'Exited with non-zero exit code'), ('time_limit_exceeded', 'Time limit exceeded'), ('memory_limit_exceeded', 'Memory limit exceeded'), ('ok', 'OK')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='should_not_be_present_verdicts',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('crashed', 'Crashed'), ('nonzero_exit_code', 'Exited with non-zero exit code'), ('time_limit_exceeded', 'Time limit exceeded'), ('memory_limit_exceeded', 'Memory limit exceeded'), ('ok', 'OK')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='solutionrunresult',
            name='verdict',
            field=models.CharField(choices=[('crashed', 'Crashed'), ('nonzero_exit_code', 'Exited with non-zero exit code'), ('time_limit_exceeded', 'Time limit exceeded'), ('memory_limit_exceeded', 'Memory limit exceeded'), ('ok', 'OK')], max_length=21, null=True, verbose_name='verdict'),
        ),
    ]
