# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 22:16
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0036_auto_20161109_0419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verifier',
            new_name='Checker',
        ),
        migrations.AlterField(
            model_name='solution',
            name='should_be_present_verdicts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('crashed', 'Crashed'), ('nonzero_exit_code', 'Exited with non-zero exit code'), ('time_limit_exceeded', 'Time limit exceeded'), ('memory_limit_exceeded', 'Memory limit exceeded'), ('ok', 'OK')], default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='should_not_be_present_verdicts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('crashed', 'Crashed'), ('nonzero_exit_code', 'Exited with non-zero exit code'), ('time_limit_exceeded', 'Time limit exceeded'), ('memory_limit_exceeded', 'Memory limit exceeded'), ('ok', 'OK')], default='', max_length=70),
            preserve_default=False,
        ),
    ]
