# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0042_auto_20161125_1007_squashed_0048_auto_20161125_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='should_be_present_verdicts',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='should_not_be_present_verdicts',
        ),
        migrations.AddField(
            model_name='solution',
            name='verdict',
            field=models.TextField(choices=[('correct', 'Correct'), ('time_limit', 'Time limit'), ('memory_limit', 'Memory limit'), ('incorrec', 'Incorrect'), ('runtime_error', 'Runtime Error')], default=0, verbose_name='verdict'),
            preserve_default=False,
        ),
    ]
