# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0043_auto_20161125_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrun',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is valid'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=models.TextField(choices=[('correct', 'Correct'), ('time_limit', 'Time limit'), ('memory_limit', 'Memory limit'), ('incorrect', 'Incorrect'), ('runtime_error', 'Runtime error'), ('failed', 'Failed'), ('time_limit_and_runtime_error', 'Time limit / Runtime error')], verbose_name='verdict'),
        ),
    ]
