# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0048_exportpackage_exportpackagecreationtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='checker',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='inputgenerator',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
    ]
