# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0049_auto_20161130_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='closed'),
        ),
    ]
