# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 17:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0006_auto_20161108_2010'),
        ('problems', '0050_discussion_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_repository.FileModel', verbose_name='file')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemRevision', verbose_name='problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problemdata',
            name='model_solution',
        ),
        migrations.AlterField(
            model_name='exportpackagecreationtask',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to='problems.ExportPackage'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=models.CharField(choices=[('model_solution', 'Model solution'), ('correct', 'Correct'), ('time_limit', 'Time limit'), ('memory_limit', 'Memory limit'), ('incorrect', 'Incorrect'), ('runtime_error', 'Runtime error'), ('failed', 'Failed'), ('time_limit_and_runtime_error', 'Time limit / Runtime error')], max_length=50, verbose_name='verdict'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
