# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0052_auto_20161201_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checker',
            old_name='source_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='inputgenerator',
            old_name='source_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='validator',
            old_name='source_file',
            new_name='file',
        ),
    ]
