# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 20:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0054_auto_20161201_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='inputgenerator',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='script',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='solutionrun',
            name='solutions',
            field=models.ManyToManyField(related_name='_solutionrun_solutions_+', to='problems.Solution', verbose_name='solution'),
        ),
        migrations.AlterField(
            model_name='solutionrun',
            name='testcases',
            field=models.ManyToManyField(related_name='_solutionrun_testcases_+', to='problems.TestCase', verbose_name='testcases'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
    ]
