# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0055_auto_20161202_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrun',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
            preserve_default=False,
        ),
    ]
