# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0051_auto_20161201_1618'),
        ('problems', '0055_auto_20161202_2041'),
    ]

    operations = [
    ]
