# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0056_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportpackage',
            name='exporter',
            field=models.CharField(choices=[('json_file', 'json_file')], max_length=20, verbose_name='exporter'),
        ),
        migrations.AlterField(
            model_name='exportpackage',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='problems.Problem'),
        ),
    ]
