# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0056_solutionrun_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='_input_generation_parameters',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='input generation command'),
        ),
    ]
