# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0061_auto_20161221_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='statement',
            field=models.TextField(default='', verbose_name='statement'),
        ),
    ]
