# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0067_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='_subtasks',
            field=models.ManyToManyField(blank=True, to='problems.Subtask', verbose_name='subtasks'),
        ),
    ]
