# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0068_auto_20170203_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision', verbose_name='head')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='role name')),
                ('permissions', models.ManyToManyField(related_name='granted_roles', to='auth.Permission', verbose_name='permissions')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='problemfork',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='problemfork',
            name='head',
        ),
        migrations.RemoveField(
            model_name='problemfork',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='problemfork',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problemfork',
            name='working_copy',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='users',
        ),
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=models.CharField(choices=[('model_solution', ('Model solution', 'AC')), ('correct', ('Correct', 'AC')), ('time_limit', ('Time limit', 'TL')), ('memory_limit', ('Memory limit', 'ML')), ('incorrect', ('Incorrect', 'WA')), ('runtime_error', ('Runtime error', 'RE')), ('failed', ('Failed', 'FL')), ('time_limit_and_runtime_error', ('Time limit / Runtime error', 'TL/RE'))], max_length=50, verbose_name='verdict'),
        ),
        migrations.AlterField(
            model_name='solutionsubtaskexpectedverdict',
            name='verdict',
            field=models.CharField(choices=[('model_solution', ('Model solution', 'AC')), ('correct', ('Correct', 'AC')), ('time_limit', ('Time limit', 'TL')), ('memory_limit', ('Memory limit', 'ML')), ('incorrect', ('Incorrect', 'WA')), ('runtime_error', ('Runtime error', 'RE')), ('failed', ('Failed', 'FL')), ('time_limit_and_runtime_error', ('Time limit / Runtime error', 'TL/RE'))], max_length=50, verbose_name='verdict'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='testcases',
            field=models.ManyToManyField(blank=True, related_name='subtasks', to='problems.TestCase', verbose_name='testcases'),
        ),
        migrations.DeleteModel(
            name='ProblemFork',
        ),
        migrations.AddField(
            model_name='problemuserrole',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors_roles', to='problems.Problem', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='problemuserrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemRole', verbose_name='role'),
        ),
        migrations.AddField(
            model_name='problemuserrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_roles', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='problembranch',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='problems.Problem', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='problembranch',
            name='working_copy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision', verbose_name='working copy'),
        ),
        migrations.AlterUniqueTogether(
            name='problemuserrole',
            unique_together=set([('user', 'problem')]),
        ),
        migrations.AlterUniqueTogether(
            name='problembranch',
            unique_together=set([('name', 'problem')]),
        ),
        migrations.AlterIndexTogether(
            name='problembranch',
            index_together=set([('name', 'problem')]),
        ),
    ]
