# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_discussion_as_topic(apps, schema_editor):
    Comment = apps.get_model("problems", "Comment")
    for comment in Comment.objects.all():
        comment.topic = comment.discussion
        comment.save()

def set_topic_as_discussion_or_delete(apps, schema_editor):
    Comment = apps.get_model("problems", "Comment")
    for comment in Comment.objects.all():
        try:
            comment.topic = comment.discussion
            comment.save()
        except Exception:
            comment.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0069_auto_20170222_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_object_id', models.PositiveIntegerField()),
                ('updated_object_id', models.PositiveIntegerField()),
                ('base_object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemBranch', verbose_name='destination branch')),
                ('participants', models.ManyToManyField(related_name='_mergerequest_participants_+', to=settings.AUTH_USER_MODEL, verbose_name='participants')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='requester')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemBranch', verbose_name='source branch')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'posting_date', 'ordering': ('topic_content_type', '-topic_id', '-posting_date')},
        ),

        migrations.AddField(
            model_name='comment',
            name='topic_content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='topic_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(set_discussion_as_topic, set_topic_as_discussion_or_delete),
        migrations.RemoveField(
            model_name='comment',
            name='discussion',
        ),
        migrations.AddField(
            model_name='approvedchange',
            name='merge_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.MergeRequest'),
        ),
        migrations.AddField(
            model_name='approvedchange',
            name='updated_object_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
    ]
