# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-31 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0076_mergerequest_reopened_by'),
        ('problems', '0078_auto_20170331_2251'),
    ]

    operations = [
    ]
