# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-07 11:10
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import problems.models.enums


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0006_auto_20161108_2010'),
        ('problems', '0080_remove_run_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionRunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', core.fields.EnumField(default='judging', enum=problems.models.enums.SolutionRunVerdict, max_length=21, verbose_name='verdict')),
                ('task_id', models.CharField(max_length=128, null=True, verbose_name='task id')),
                ('execution_message', models.TextField(null=True, verbose_name='execution message')),
                ('score', models.FloatField(null=True, verbose_name='score')),
                ('contestant_message', models.TextField(null=True, verbose_name='checker comment to contestant')),
                ('solution_execution_time', models.FloatField(null=True, verbose_name='solution execution time')),
                ('solution_memory_usage', models.IntegerField(null=True, verbose_name='solution memory usage')),
                ('checker_standard_error', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='checker standard error')),
                ('checker_standard_output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='checker standard output')),
                ('solution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='problems.Solution', verbose_name='solution')),
                ('solution_output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='solution output file')),
                ('solution_run', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='problems.SolutionRun', verbose_name='solution run')),
            ],
        ),
        migrations.DeleteModel(
            name='CompileJob',
        ),
        migrations.DeleteModel(
            name='ExportPackageCreationTask',
        ),
        migrations.DeleteModel(
            name='TestCaseGeneration',
        ),
        migrations.DeleteModel(
            name='TestCaseValidation',
        ),
        migrations.RenameField(
            model_name='checker',
            old_name='_compiled_file',
            new_name='compiled_file',
        ),
        migrations.RenameField(
            model_name='inputgenerator',
            old_name='_compiled_file',
            new_name='compiled_file',
        ),
        migrations.RenameField(
            model_name='validator',
            old_name='_compiled_file',
            new_name='compiled_file',
        ),
        migrations.AddField(
            model_name='checker',
            name='compilation_finished',
            field=models.BooleanField(default=False, verbose_name='compilation finished'),
        ),
        migrations.AddField(
            model_name='checker',
            name='compilation_task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='compilation task id'),
        ),
        migrations.AddField(
            model_name='inputgenerator',
            name='compilation_finished',
            field=models.BooleanField(default=False, verbose_name='compilation finished'),
        ),
        migrations.AddField(
            model_name='inputgenerator',
            name='compilation_task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='compilation task id'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='generation_task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='generation task id'),
        ),
        migrations.AddField(
            model_name='validator',
            name='compilation_finished',
            field=models.BooleanField(default=False, verbose_name='compilation finished'),
        ),
        migrations.AddField(
            model_name='validator',
            name='compilation_task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='compilation task id'),
        ),
        migrations.AddField(
            model_name='validatorresult',
            name='task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='task id'),
        ),

        migrations.AddField(
            model_name='solutionrunresult',
            name='testcase',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='problems.TestCase', verbose_name='testcase'),
        ),
        migrations.AlterUniqueTogether(
            name='solutionrunresult',
            unique_together=set([('solution_run', 'solution', 'testcase')]),
        ),
    ]
