# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-03 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0086_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='judge_initialization_successful',
            field=models.NullBooleanField(default=None, verbose_name='initialization finished'),
        ),
    ]
