# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-04 10:03
from __future__ import unicode_literals

from django.db import migrations

def unique_object_name(objects):
    names = {}
    for object in objects.all():
        while object.name in names:
            cnt = names[object.name]
            names[object.name] = cnt + 1

            object.name = "{}({})".format(object.name, cnt)
        object.save()
        names[object.name] = 1


def unique_graders_and_solutions(apps, schema_editor):
    from problems.models import ProblemRevision

    print("renaming duplicate objects!")
    total = ProblemRevision.objects.count()

    for i, problemRevision in enumerate(ProblemRevision.objects.all()):
        if i == 0 or 100 * (i - 1) // total != 100 * i // total:
            print("{}%".format(100 * i // total))
        unique_object_name(problemRevision.subtasks.all())
        unique_object_name(problemRevision.grader_set.all())


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0089_auto_20170528_1259'),
    ]

    operations = [
        migrations.RunPython(unique_graders_and_solutions, migrations.RunPython.noop),

    ]
