# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0090_auto_20170604_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportpackage',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.AddField(
            model_name='exportpackage',
            name='creation_successful',
            field=models.NullBooleanField(verbose_name='creation success'),
        ),
        migrations.AddField(
            model_name='exportpackage',
            name='creation_task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='creation task id'),
        ),
    ]
