# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-05 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0091_auto_20170605_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ('problem', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='grader',
            unique_together=set([('problem', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together=set([('problem', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='checker',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='grader',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='inputgenerator',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='resource',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='solution',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='subtask',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='testcase',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='validator',
            index_together=set([('problem', 'name')]),
        ),
    ]
