# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-15 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0094_merge'),
        ('problems', '0090_merge'),
    ]

    operations = [
    ]
