# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-29 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0091_problem_repository_path'),
        ('problems', '0095_merge'),
    ]

    operations = [
    ]
