# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-04 16:32
from __future__ import unicode_literals

from django.db import migrations
import problems.models.fields
import problems.models.solution
import problems.models.testdata


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0097_auto_20170629_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrun',
            name='solutions',
            field=problems.models.fields.DBToGitManyToManyField(commit_id_field_name='commit_id', default='', problem_field_name='base_problem', to=problems.models.solution.Solution, verbose_name='solution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutionrun',
            name='testcases',
            field=problems.models.fields.DBToGitManyToManyField(commit_id_field_name='commit_id', default='', problem_field_name='base_problem', to=problems.models.testdata.TestCase, verbose_name='testcases'),
            preserve_default=False,
        ),
    ]
