# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0102_auto_20170705_2346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solutionrunresult',
            unique_together=set([('solution_run', 'solution', 'testcase')]),
        ),
    ]
