# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('commited', models.BooleanField(default=False, help_text='', verbose_name='commited')),
            ],
        ),
    ]
