# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
