# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileModel'
        ),
    ]
