# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0002_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='commited',
        ),
    ]
