# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0005_auto_20161011_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='name'),
        ),
    ]
