# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-29 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0006_auto_20161108_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSystemModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='GitBinaryFile',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='GitFile',
            fields=[
            ],
        ),
    ]
