# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='execution_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='success',
            field=models.NullBooleanField(),
        ),
    ]
