# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_auto_20160803_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='command',
            new_name='_command',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='jobfile',
            unique_together=set([('job_model', 'filename', 'type')]),
        ),
    ]
