# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='SourceFile',
            old_name='file',
            new_name='source_file'
        )
    ]
