# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_auto_20160830_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='Untitled', max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='name',
            field=models.CharField(default='Untitled', max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='source_language',
            field=models.CharField(choices=[('c++', 'c++')], max_length=200, null=True),
        ),
    ]
