# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_auto_20161007_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='testcase_number',
            field=models.IntegerField(default=0, verbose_name='testcase_number'),
            preserve_default=False,
        ),
    ]
