# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0024_auto_20161011_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='_output_file',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel'),
        ),
    ]
