# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_auto_20161025_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionrunresult',
            name='verdict',
            field=models.CharField(choices=[('crashed', 'Crashed'), ('nonzero_exit_code', 'Exited with non-zero exit code'), ('time_limit_exceeded', 'Time limit exceeded'), ('memory_limit_exceeded', 'Memory limit exceeded')], max_length=21, verbose_name='verdict'),
        ),
    ]
