# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 09:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0031_auto_20161029_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_file_name', message='please enter a valid file name.', regex='[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_file_name', message='please enter a valid file name.', regex='[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*')], verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcefile',
            unique_together=set([('problem', 'name')]),
        ),
    ]
