# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 09:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0038_solution_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='should_be_present_verdicts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('invalid_submission', 'Invalid Submission'), ('crashed', 'Crashed'), ('nonzero_exit_code', 'Exited with non-zero exit code'), ('time_limit_exceeded', 'Time limit exceeded'), ('memory_limit_exceeded', 'Memory limit exceeded'), ('ok', 'OK')], max_length=89),
        ),
        migrations.AlterField(
            model_name='solution',
            name='should_not_be_present_verdicts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('invalid_submission', 'Invalid Submission'), ('crashed', 'Crashed'), ('nonzero_exit_code', 'Exited with non-zero exit code'), ('time_limit_exceeded', 'Time limit exceeded'), ('memory_limit_exceeded', 'Memory limit exceeded'), ('ok', 'OK')], max_length=89),
        ),
        migrations.AlterField(
            model_name='solutionrunresult',
            name='verdict',
            field=models.CharField(choices=[('invalid_submission', 'Invalid Submission'), ('crashed', 'Crashed'), ('nonzero_exit_code', 'Exited with non-zero exit code'), ('time_limit_exceeded', 'Time limit exceeded'), ('memory_limit_exceeded', 'Memory limit exceeded'), ('ok', 'OK')], max_length=21, null=True, verbose_name='verdict'),
        ),
    ]
