# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0045_auto_20161126_0758'),
        ('problems', '0043_auto_20161126_0645'),
    ]

    operations = [
    ]
