# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0046_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemfork',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision', verbose_name='head'),
        ),
    ]
