# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trader.exporters.json


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_repository', '0006_auto_20161108_2010'),
        ('tasks', '0001_initial'),
        ('problems', '0047_auto_20161128_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('exporter', models.CharField(choices=[('json_file', trader.exporters.json.JSONExporter)], max_length=20, verbose_name='exporter')),
                ('export_format', models.CharField(choices=[('zip', 'zip'), ('tar', 'tar')], default='zip', max_length=20, verbose_name='export format')),
                ('archive', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_repository.FileModel', verbose_name='archive')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='problems.ProblemRevision')),
            ],
        ),
        migrations.CreateModel(
            name='ExportPackageCreationTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ExportPackage')),
            ],
            bases=('tasks.task',),
        ),
    ]
