# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0050_discussion_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportpackagecreationtask',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to='problems.ExportPackage'),
        ),
    ]
