# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 21:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0006_auto_20161108_2010'),
        ('problems', '0051_auto_20161201_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='inputgenerator',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_file_name', inverse_match=False, message='Please enter a valid file name.', regex='^[a-zA-Z0-9_\\-](?:\\.|[a-zA-Z0-9_\\-])*$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='file_repository.FileModel', verbose_name='file'),
        ),

    ]
