# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0053_auto_20161201_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('problem', 'name')]),
        ),
    ]
