# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('problems', '0055_auto_20161202_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseValidation',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
            ],
            bases=('tasks.task',),
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='_input_generation_log',
            new_name='input_generation_log',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='_input_generation_successful',
            new_name='input_generation_successful',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='_input_static',
            new_name='input_static',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='_output_generation_log',
            new_name='output_generation_log',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='_output_generation_successful',
            new_name='output_generation_successful',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='_output_static',
            new_name='output_static',
        ),
        migrations.DeleteModel(
                'validatorresult'
        ),
        migrations.AlterField(
            model_name='solution',
            name='subtask_scores',
            field=models.ManyToManyField(related_name='_solution_subtask_scores_+', through='problems.SolutionSubtaskExpectedScore', to='problems.Subtask'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='tests_scores',
            field=models.ManyToManyField(related_name='_solution_tests_scores_+', through='problems.SolutionTestExpectedScore', to='problems.TestCase'),
        ),
        migrations.AddField(
            model_name='testcasevalidation',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.TestCase'),
        ),
        migrations.AddField(
            model_name='testcasevalidation',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Validator'),
        ),
    ]
