# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0057_auto_20161204_1831'),
        ('problems', '0057_auto_20161208_0825'),
    ]

    operations = [
    ]
