# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0058_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_generation_log',
            field=models.TextField(null=True, verbose_name='input generation log'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_generation_log',
            field=models.TextField(null=True, verbose_name='output generation log'),
        ),
    ]
