# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0059_auto_20161208_1355'),
        ('problems', '0057_auto_20161204_2149'),
    ]

    operations = [
    ]
