# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0060_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionrunresult',
            old_name='verdict',
            new_name='solution_verdict',
        ),
        migrations.AlterField(
            model_name='solutionrunresult',
            name='solution_verdict',
            field=models.CharField(choices=[('invalid_submission', ('Bad Submission', 'BS')), ('compilation_failed', ('Compilation Error', 'CE')), ('runtime_error', ('Runtime error', 'RE')), ('time_limit_exceeded', ('Time limit exceeded', 'TLE')), ('memory_limit_exceeded', ('Memory limit exceeded', 'MLE')), ('ok', ('OK', 'OK')), ('checker_failed', ('Checker failed', 'CHKFL')), ('invalid_testcase', ('Invalid testcase', 'INVLDTC')), ('judge_failed', ('Judge failed', 'JUDFL'))], max_length=21, null=True, verbose_name='verdict'),
        ),
    ]
