# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0063_first_problem'),
        ('problems', '0063_auto_20170107_0748'),
    ]

    operations = [
    ]
