# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0062_grader'),
        ('problems', '0066_auto_20170202_2109'),
    ]

    operations = [
    ]
