# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0070_auto_20170227_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergerequest',
            name='status',
            field=models.CharField(choices=[('1', 'open'), ('2', 'closed'), ('3', 'merged')], default='1', max_length=100),
        ),
    ]
