# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 23:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0073_auto_20170301_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ('problem', 'name')},
        ),
        migrations.AlterField(
            model_name='problembranch',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^\\w{1,30}$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=models.CharField(choices=[('model_solution', 'Model solution'), ('correct', 'Correct'), ('time_limit', 'Time limit'), ('memory_limit', 'Memory limit'), ('incorrect', 'Incorrect'), ('runtime_error', 'Runtime error'), ('failed', 'Failed'), ('time_limit_and_runtime_error', 'Time limit / Runtime error')], max_length=50, verbose_name='verdict'),
        ),
    ]
