# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-28 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0075_mergerequest_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problembranch',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='problems.ProblemRevision', verbose_name='head'),
        ),
        migrations.AlterField(
            model_name='problembranch',
            name='working_copy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='problems.ProblemRevision', verbose_name='working copy'),
        ),
    ]
