# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0075_mergerequest_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergerequest',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reopened by'),
        ),
    ]
