# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-28 21:40
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import problems.models.enums


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0076_auto_20170328_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionrunresult',
            name='checker_execution_message',
        ),
        migrations.RemoveField(
            model_name='solutionrunresult',
            name='checker_execution_success',
        ),
        migrations.RemoveField(
            model_name='solutionrunresult',
            name='solution_execution_message',
        ),
        migrations.RemoveField(
            model_name='solutionrunresult',
            name='solution_execution_success',
        ),
        migrations.RemoveField(
            model_name='solutionrunresult',
            name='solution_verdict',
        ),
        migrations.AddField(
            model_name='solutionrunresult',
            name='execution_message',
            field=models.TextField(null=True, verbose_name='execution message'),
        ),
        migrations.AddField(
            model_name='solutionrunresult',
            name='verdict',
            field=core.fields.EnumField(default='judging', enum=problems.models.enums.SolutionRunVerdict, max_length=21, verbose_name='verdict'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=core.fields.EnumField(enum=problems.models.enums.SolutionVerdict, max_length=50, verbose_name='verdict'),
        ),
        migrations.AlterField(
            model_name='solutionsubtaskexpectedverdict',
            name='verdict',
            field=core.fields.EnumField(enum=problems.models.enums.SolutionVerdict, max_length=50, verbose_name='verdict'),
        ),
    ]
