# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0006_auto_20161108_2010'),
        ('problems', '0079_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='files',
            field=models.ManyToManyField(to='file_repository.FileModel', verbose_name='problem files'),
        ),
    ]
