# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-27 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0082_auto_20170426_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemrevision',
            name='judge_code',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='generation_task_id',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='judge_code',
        ),
        migrations.AddField(
            model_name='problemrevision',
            name='judge_initialization_message',
            field=models.CharField(default='', max_length=256, verbose_name='initialization message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemrevision',
            name='judge_initialization_successful',
            field=models.NullBooleanField(verbose_name='initialization success'),
        ),
        migrations.AddField(
            model_name='problemrevision',
            name='judge_initialization_task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='initialization task id'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_generation_task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='input generation task id'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='judge_initialization_message',
            field=models.CharField(default='', max_length=256, verbose_name='initialization message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='judge_initialization_successful',
            field=models.BooleanField(default=False, verbose_name='initialization finished'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='judge_initialization_task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='initialization task id'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output_generation_task_id',
            field=models.CharField(max_length=128, null=True, verbose_name='output generation task id'),
        ),
    ]
