# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0080_problem_files'),
        ('problems', '0084_auto_20170427_0939'),
    ]

    operations = [
    ]
