# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0085_auto_20170501_0904'),
        ('problems', '0085_merge'),
    ]

    operations = [
    ]
