# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-04 10:03
from __future__ import unicode_literals

from django.db import migrations

def unique_object_name(objects):
    names = {}
    for object in objects.all():
        while object.name in names:
            cnt = names[object.name]
            names[object.name] = cnt + 1

            object.name = "{}({})".format(object.name, cnt)
        object.save()
        names[object.name] = 1


def unique_graders_and_solutions(apps, schema_editor):
    from problems.models import InputGenerator, ProblemRevision

    disabled_generators = []

    print("disabling generators...")
    total = InputGenerator.objects.count()

    for i, generator in enumerate(InputGenerator.objects.all()):

        if i == 0 or 100 * (i - 1) // total != 100 * i // total:
            print("{}%".format(100 * i // total))

        if generator.is_enabled:
            generator.disable()
            disabled_generators.append(generator)

    print("renaming duplicate testcases!")
    total = ProblemRevision.objects.count()

    for i, problemRevision in enumerate(ProblemRevision.objects.all()):
        if i == 0 or 100 * (i - 1) // total != 100 * i // total:
            print("{}%".format(100 * i // total))
        unique_object_name(problemRevision.subtasks.all())
        unique_object_name(problemRevision.grader_set.all())

    print('enabling disabled generators...')
    total = len(disabled_generators)

    for i, generator in enumerate(disabled_generators):
        if i == 0 or 100*(i-1)//total != 100*i//total:
            print("{}%".format(100*i//total))
        try:
            generator.enable()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0089_auto_20170528_1259'),
    ]

    operations = [
        migrations.RunPython(unique_graders_and_solutions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ('problem', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='grader',
            unique_together=set([('problem', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='checker',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='grader',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='inputgenerator',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='resource',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='solution',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='subtask',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='testcase',
            index_together=set([('problem', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='validator',
            index_together=set([('problem', 'name')]),
        ),
    ]
