# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-22 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0090_auto_20170604_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='repository_path',
            field=models.CharField(blank=True, max_length=256, verbose_name='repository path'),
        ),
    ]
