# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0092_auto_20170605_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemrevision',
            name='judge_initialization_successful',
            field=models.NullBooleanField(default=None, verbose_name='initialization success'),
        ),
    ]
