# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0093_auto_20170605_1457'),
        ('problems', '0087_auto_20170603_1827'),
    ]

    operations = [
    ]
