# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0099_auto_20170704_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='code'),
        ),
    ]
