# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-05 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0101_auto_20170705_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='code'),
        ),
    ]
