# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0104_solutionrun_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportpackage',
            name='revision',
        ),
        migrations.AddField(
            model_name='exportpackage',
            name='commit_id',
            field=models.CharField(default='', max_length=256, verbose_name='commit id'),
            preserve_default=False,
        ),
    ]
