# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import problems.models.solution_run


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0105_auto_20170712_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solutionrun',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.AddField(
            model_name='solutionrun',
            name='repeat_executions',
            field=models.PositiveIntegerField(default=1, validators=[problems.models.solution_run.validate_nonzero_executions], verbose_name='number of executions'),
        ),
        migrations.AddField(
            model_name='solutionrunresult',
            name='solution_max_execution_time',
            field=models.FloatField(null=True, verbose_name='solution max execution time'),
        ),
        migrations.AddField(
            model_name='solutionrunresult',
            name='solution_min_execution_time',
            field=models.FloatField(null=True, verbose_name='solution min execution time'),
        ),
    ]
