# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170222_1647'),
        ('problems', '0069_auto_20170222_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProblem',
        ),
    ]
