# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_reference_key', models.CharField(max_length=256, null=True, verbose_name='queue reference key')),
                ('state', models.CharField(choices=[('created', 'Created'), (('queued',), 'Queued'), (('running',), 'Running'), ('finished', 'Finished')], default='created', max_length=20, verbose_name='state')),
            ],
        ),
    ]
